spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/supershop
      database: supershop
      auto-index-creation: true 
  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false